#! /bin/sh

NAME=crond

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
  . /etc/default/$NAME
fi

case "$1" in
  start)
    printf "Starting $NAME: "
    mkdir -p /var/spool/cron/crontabs
    find /etc/cron.d -type f -name '*.cron' -exec cat {} + >> /var/spool/cron/crontabs/root
    start-stop-daemon -S -q -x /usr/sbin/crond -b
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping $NAME: "
    rm -rf /var/spool/cron
    start-stop-daemon -K -q -n $NAME
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    echo "Restarting $NAME: "
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
